import React, { Suspense, lazy, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowDown, ArrowRight, Download, Menu, X, Code2, Layers3, Sparkles, Globe2, Check, Copy, MapPin, ChevronRight, Command, CalendarDays, Users, LayoutDashboard, BookOpen, Plus } from 'lucide-react';
import './styles.css';

const Sculpture = lazy(() => import('./Sculpture.jsx'));
const resume = '/Om_Zala_Resume_2026.pdf';
function Github({ size = 24 }) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M9 19c-4.3 1.3-4.3-2.2-6-2.7m12 5v-3.4c.1-1-.3-1.8-.8-2.2 2.8-.3 5.8-1.4 5.8-6.2 0-1.4-.5-2.5-1.3-3.4.1-.3.6-1.6-.1-3.4 0 0-1.1-.4-3.6 1.3a12 12 0 0 0-6 0C6.5 2.3 5.4 2.7 5.4 2.7c-.7 1.8-.2 3.1-.1 3.4C4.5 7 4 8.1 4 9.5c0 4.8 3 5.9 5.8 6.2-.5.4-.9 1.3-.8 2.2v3.4"/></svg>; }
function Linkedin({ size = 24 }) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M7 10v7M11 17v-7m0 3a3 3 0 0 1 6 0v4"/><circle cx="7" cy="7" r=".5" fill="currentColor"/></svg>; }
const projects = [
  { id: 'agentvisit', name: 'AgentVisit', category: 'AI & automation', filter: 'AI & automation', type: 'AI-POWERED FIELD OPERATIONS', description: 'Less paperwork. More possibilities. An intelligent platform that connects field teams, automates visit reports, and keeps every visit on track.', tags: ['React', 'Node.js', 'MongoDB', 'Gemini AI'], role: 'Sole developer', url: 'https://kagentvisit.vercel.app/', color: 'violet', features: ['AI-generated field visit reports with the Gemini API', 'Google Calendar scheduling and Google Maps integration', 'Multi-tier access for administrators, field agents, and accounts'] },
  { id: 'edushine', name: 'Edushine', category: 'Full stack', filter: 'Full stack', type: 'A MORE CONNECTED CLASSROOM', description: 'Bringing students, teachers, and parents together. A complete learning platform that turns everyday coordination into a seamless experience.', tags: ['React', 'Express', 'MongoDB', 'RBAC'], role: 'Sole developer', url: 'https://edushinestudyhub.com/', color: 'peach', features: ['Four dedicated roles: admin, teacher, student, and parent', 'Student enrollment and teacher hiring workflows', 'Assignment management and parent reporting'] },
  { id: 'travel', name: 'Travel CRM', category: 'Full stack', filter: 'Full stack', type: 'FROM FIRST HELLO TO TAKEOFF', description: 'A unified workspace for travel teams. Manage leads, organize opportunities, and bring real-time booking inventory into one connected workflow.', tags: ['React', 'Node.js', 'MongoDB', 'TBO API'], role: 'Sole developer', color: 'blue', features: ['Kanban-style lead and opportunity pipelines', 'Ticketing and travel package management', 'TBO API integration for live travel inventory and booking data'] },
  { id: 'junohub', name: 'Junohub', category: 'Web experiences', filter: 'Web experiences', type: 'SPACE FOR THE NEXT BIG THING', description: 'A digital home for emerging businesses. Custom interactions and thoughtful design connect entrepreneurs with workspace, mentorship, and resources.', tags: ['React', 'Node.js', 'MongoDB', 'UI animation'], role: 'Lead developer', url: 'https://junohub.co/', color: 'green', features: ['Platform for workspace, mentorship, and business resources', 'Custom React animations and interactive effects', 'Full-stack development using the MERN stack'] },
  { id: 'tasks', name: 'Task Manager + MOM', filter: 'Full stack', type: 'TURN CONVERSATIONS INTO PROGRESS', description: 'A shared home for tasks, meetings, and the decisions that move teams forward.', tags: ['React', 'Express', 'MongoDB'], role: 'Sole developer', url: 'https://task-manager-mom.vercel.app/', color: 'violet', features: ['Kanban task tracking and role-based access', 'Meeting scheduling, minutes drafting, and approvals', 'Real-time notifications'] },
  { id: 'pms', name: 'Performance Management', filter: 'Full stack', type: 'GROWTH, WITH A CLEARER PICTURE', description: 'Employee goals, performance reviews, and useful reporting in one role-aware platform.', tags: ['React', 'Node.js', 'MongoDB'], role: 'Team project', url: 'https://github.com/Omzala/PMS-Project', color: 'blue', features: ['Four-role access hierarchy', 'Goal-setting cycles and performance reviews', 'Reporting dashboards'] },
  { id: 'academy', name: 'AI Skill Academy', filter: 'Web experiences', type: 'A BETTER PLACE TO BUILD SKILLS', description: 'A responsive, design-forward e-learning experience for a design and frontend course.', tags: ['React', 'Express', 'MongoDB'], role: 'Sole developer', url: 'https://aiskillacademy.vercel.app/', color: 'peach', features: ['Full-stack e-learning application', 'Design and frontend course delivery', 'Responsive, design-forward interface'] },
  { id: 'wealth', name: 'WealthWise', filter: 'Full stack', type: 'MAKE SENSE OF YOUR MONEY', description: 'A personal finance tracker that brings income, expenses, and spending patterns into focus.', tags: ['Python', 'JavaScript', 'MongoDB'], role: 'Primary developer', url: 'https://github.com/Omzala/Wealthwise', color: 'green', features: ['Income and expense tracking', 'Interactive charts for spending patterns', 'MongoDB-backed financial records'] },
  { id: 'events', name: 'AI Skill Events', filter: 'Web experiences', type: 'WHERE CURIOUS MINDS CONNECT', description: 'A fast, responsive registration and information website for an AI hackathon.', tags: ['React', 'Tailwind CSS'], role: 'Sole developer', url: 'https://ai-skill-events.vercel.app/', color: 'violet', features: ['Hackathon information and registration site', 'Responsive layouts', 'Optimized for fast page loads'] },
];

function ProjectArt({ project }) {
  if (project.id === 'agentvisit') return <div className="art art-agent" aria-hidden="true"><div className="art-orbit" /><div className="mini-app"><div className="mini-sidebar"><span className="mini-brand"><Command size={15} /> av.</span><LayoutDashboard /><CalendarDays /><Users /><MapPin /><span className="mini-avatar">O</span></div><div className="mini-content"><div className="mini-header"><span>Overview <small>Welcome back, Om 👋</small></span><span className="mini-date">Field operations <ChevronRight size={10} /></span></div><div className="mini-stats"><div><span>Total visits</span><strong>128 <small>↗ 18%</small></strong></div><div><span>Completed</span><strong>96 <small>↗ 12%</small></strong></div><div><span>Active agents</span><strong>24 <i /></strong></div></div><div className="mini-map"><svg viewBox="0 0 350 115"><defs><pattern id="map-grid" width="50" height="40" patternUnits="userSpaceOnUse"><path d="M 50 0 L 0 0 0 40" fill="none" stroke="#383148" strokeWidth="8" /></pattern></defs><rect width="350" height="115" fill="url(#map-grid)"/><path d="M35 95Q100 130 130 60T290 30" fill="none" stroke="#a998ed" strokeWidth="2" strokeDasharray="5 4"/><circle cx="130" cy="60" r="8" fill="#c9b9ff"/><circle cx="290" cy="30" r="6" fill="#c9b9ff"/></svg><span><i /> Live field activity</span></div></div></div><div className="ai-float"><Sparkles size={16}/><div>Visit report generated<small>A little AI. A lot less busywork.</small></div><Check size={13}/></div></div>;
  if (project.id === 'edushine') return <div className="art art-edu" aria-hidden="true"><div className="edu-window"><div className="edu-nav"><span><span className="edu-logo">e</span> edushine.</span><span>Learning, made brighter <ArrowUpRight size={12}/></span></div><div className="edu-layout"><div><span className="tiny-label">YOUR NEXT CHAPTER STARTS HERE</span><h4>Small steps.<br/>Bright futures<span>.</span></h4><p>A space to learn, grow,<br/>and shine together.</p><span className="edu-button">Let's get learning <ArrowUpRight size={11}/></span></div><div className="edu-shapes"><div className="edu-flower">✳</div><div className="edu-circle"><BookOpen size={30}/></div><div className="edu-check"><Check size={29}/></div></div></div><div className="edu-bottom"><span>FOR THE CURIOUS. FOR THE AMBITIOUS.</span><span>✦</span></div></div><div className="edu-float"><span>✦</span> A brighter way to learn</div></div>;
  if (project.id === 'travel') return <div className="art art-travel" aria-hidden="true"><div className="travel-window"><div className="travel-nav"><span><Globe2 size={16}/> travel<span className="muted">crm</span></span><span>Workspace <span className="mini-avatar">O</span></span></div><div className="travel-title"><div><span className="tiny-label">YOUR NEXT OPPORTUNITY</span><h4>Every journey starts here.</h4></div><span className="travel-add"><Plus size={11}/> New lead</span></div><div className="kanban">{['New leads', 'In progress', 'Ready to book'].map((name, i) => <div key={name}><div className="kanban-label"><i/>{name}<span>{[4,3,2][i]}</span></div>{[0,1].map((n) => <div className="kanban-card" key={n}><span className="kanban-tag">{['Leisure','Corporate','Package'][i]}</span><strong>{[['Bali escape','European summer'],['Dubai getaway','Singapore retreat'],['Swiss adventure','Island hopping']][i][n]}</strong><span className="kanban-line"/><div><span>{['7 nights · 2 guests','5 nights · 4 guests'][n]}</span><span className="kanban-person">{['AK','OM','JD'][i]}</span></div></div>)}</div>)}</div></div><div className="travel-stamp"><Globe2 size={17}/><span>Ideas to itineraries.</span></div></div>;
  if (project.id === 'junohub') return <div className="art art-juno" aria-hidden="true"><div className="juno-window"><div className="juno-nav"><strong>juno<span>hub</span>✳</strong><span>The space. The people. The possibilities.</span><Menu size={13}/></div><div className="juno-title"><span>GOOD IDEAS DESERVE GREAT COMPANY.</span><h4>Big ideas.<br/>Meet your <em>space.</em></h4><span className="juno-button">Find your place <ArrowUpRight size={12}/></span></div><div className="juno-sculpture"><span/><span/><span/><span/></div><div className="juno-bottom"><span>WORK. CONNECT. GROW.</span><ArrowDown size={14}/></div></div></div>;
  return <div className={`art art-extra ${project.color}`} aria-hidden="true"><div className="extra-grid"/><div className="extra-icon">{project.id === 'wealth' ? <span>₹</span> : project.id === 'tasks' ? <LayoutDashboard/> : project.id === 'pms' ? <Users/> : <Sparkles/>}</div><span className="extra-title">{project.name}</span><span className="extra-subtitle">{project.type}</span></div>;
}

function ProjectDialog({ project, onClose }) {
  const dialog = useRef(null);
  useEffect(() => {
    const element = dialog.current;
    const previous = document.activeElement;
    const overflow = document.body.style.overflow;
    element.showModal();
    document.body.style.overflow = 'hidden';
    return () => {
      element.close();
      document.body.style.overflow = overflow;
      previous?.focus({ preventScroll: true });
    };
  }, []);
  return <dialog ref={dialog} className="project-dialog" onCancel={onClose} onClick={e => { if (e.target === e.currentTarget) onClose(); }} aria-labelledby="project-title"><div className="dialog-inner"><button className="icon-button dialog-close" onClick={onClose} aria-label="Close project"><X/></button><span className="eyebrow">PROJECT SPOTLIGHT / {project.role}</span><h2 id="project-title">{project.name}<span>.</span></h2><p>{project.description}</p><div className="dialog-tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div><h3>What I built</h3><ul>{project.features.map(feature => <li key={feature}><Check size={16}/>{feature}</li>)}</ul>{project.url ? <a className="button button-primary" href={project.url} target="_blank" rel="noreferrer">{project.url.includes('github') ? 'Explore the code' : 'Visit project'} <ArrowUpRight size={18}/></a> : <p className="private-note"><Layers3 size={17}/> Business application · Public demo unavailable</p>}<small className="preview-note">Portfolio artwork is an illustrative preview, not a live screenshot.</small></div></dialog>;
}

function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [filter, setFilter] = useState('All work');
  const [expanded, setExpanded] = useState(false);
  const [selected, setSelected] = useState(null);
  const [copied, setCopied] = useState(false);
  const [copyError, setCopyError] = useState(false);
  const [time, setTime] = useState('');
  useEffect(() => {
    const update = () => setTime(new Intl.DateTimeFormat('en-GB', { timeZone: 'Asia/Kolkata', hour: '2-digit', minute: '2-digit', hour12: false }).format(new Date()));
    update(); const interval = setInterval(update, 60000);
    const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('visible'); observer.unobserve(entry.target); } }), { threshold: .08 });
    document.querySelectorAll('.reveal').forEach(el => observer.observe(el));
    return () => { clearInterval(interval); observer.disconnect(); };
  }, []);
  useEffect(() => { if (!menuOpen) return; const close = e => { if (e.key === 'Escape') setMenuOpen(false); }; document.addEventListener('keydown', close); return () => document.removeEventListener('keydown', close); }, [menuOpen]);
  const copyEmail = async () => { try { await navigator.clipboard.writeText('omzala635@gmail.com'); setCopied(true); setCopyError(false); setTimeout(() => setCopied(false), 2500); } catch { setCopyError(true); } };
  const filtered = projects.filter(p => filter === 'All work' || p.filter === filter);
  const visibleProjects = expanded ? filtered : filtered.slice(0, 4);
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="site-header"><a className="wordmark" href="#home" aria-label="Om Zala home">om<span>zala</span><i/></a><nav id="mobile-nav" className={menuOpen ? 'navigation open' : 'navigation'} aria-label="Main navigation">{[['Work', 'work'], ['About', 'about'], ['Experience', 'experience']].map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => setMenuOpen(false)}>{label}</a>)}<a className="nav-contact" href="#contact" onClick={() => setMenuOpen(false)}>Let's talk <ArrowUpRight size={15}/></a></nav><a className="header-availability" href="#contact"><span className="status-dot"/> Open to opportunities</a><button className="mobile-toggle icon-button" aria-expanded={menuOpen} aria-controls="mobile-nav" aria-label={menuOpen ? 'Close navigation' : 'Open navigation'} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X/> : <Menu/>}</button></header>
    <main id="main">
      <section id="home" className="hero section-shell"><div className="hero-copy"><div className="hero-kicker"><span className="small-line"/> DEVELOPER BY CRAFT. CREATOR AT HEART.</div><h1>Turning ideas<br/>into <span className="serif-word">extraordinary</span><br/>digital experiences<span className="lime-period">.</span></h1><p className="hero-description">Hey, I'm <strong>Om Zala</strong> — a full stack developer blending<br className="desktop-break"/> thoughtful design, clean code, and a little AI magic.</p><div className="hero-actions"><a className="button button-primary" href="#work">Explore my work <ArrowUpRight size={19}/></a><a className="button button-text" href={resume} download>Download résumé <Download size={16}/></a></div><div className="hero-location"><MapPin size={13}/><span>Vadodara, India</span><span className="location-divider"/><span>Building for everywhere</span></div></div><div className="hero-art"><div className="art-coordinate top">FIG. 01 — IDEAS IN MOTION</div><div className="sculpture-glow"/><div className="sculpture-wrap"><Suspense fallback={<div className="sculpture-fallback"/>}><Sculpture/></Suspense></div><div className="floating-label label-code"><Code2 size={15}/><span>Logic meets imagination</span></div><div className="floating-label label-ai"><Sparkles size={14}/><span>Built with curiosity</span></div><div className="art-coordinate bottom"><span className="crosshair">+</span> INTERACTIVE OBJECT · MOVE YOUR CURSOR <span className="crosshair">+</span></div></div><div className="hero-bottom"><div className="hero-stats"><div><strong>10<span>+</span></strong><span>Projects shipped</span></div><div><strong>1<span>+</span></strong><span>Year of experience</span></div><div><strong>∞</strong><span>Curiosity to create</span></div></div><a className="scroll-cue" href="#work"><span>SCROLL TO EXPLORE</span><span className="scroll-circle"><ArrowDown size={17}/></span></a></div></section>
      <div className="ticker" aria-label="Full stack development, creative interfaces, intelligent integrations"><div className="ticker-track">{[0,1,2,3].map(i => <div className="ticker-group" key={i} aria-hidden={i > 0}><span>FULL STACK DEVELOPMENT</span><span className="ticker-star">✳</span><span>CREATIVE INTERFACES</span><span className="ticker-star">✳</span><span>INTELLIGENT INTEGRATIONS</span><span className="ticker-star">✳</span></div>)}</div></div>
      <section id="work" className="work-section section-shell"><div className="section-heading reveal"><div><div className="eyebrow"><span className="section-number">01 /</span> SELECTED WORK</div><h2>Made with intent.<br/>Built to <span className="serif-word">make a difference.</span></h2></div><p>A few things I've taken from<br/>“what if” to out in the world.</p></div><div className="work-controls reveal"><div className="filters" role="group" aria-label="Filter projects">{['All work', 'Full stack', 'AI & automation', 'Web experiences'].map(item => <button key={item} className={filter === item ? 'filter active' : 'filter'} aria-pressed={filter === item} onClick={() => { setFilter(item); setExpanded(false); }}>{item}{item === 'All work' && <span>09</span>}</button>)}</div><span className="project-count">{String(filtered.length).padStart(2, '0')} PROJECTS</span></div><div className="project-grid">{visibleProjects.map((project, i) => <button className={`project-card ${project.color}`} key={project.id} onClick={() => setSelected(project)} aria-label={`View ${project.name} project details`}><div className="project-image"><ProjectArt project={project}/><span className="project-open"><ArrowUpRight size={21}/></span><span className="project-art-label">INTERFACE CONCEPT</span></div><div className="project-info"><div><span className="project-type">{project.type}</span><h3>{project.name}</h3></div><span className="project-index">/{String(i + 1).padStart(2, '0')}</span></div><div className="project-tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div></button>)}</div>{filtered.length > 4 && <div className="more-work"><button className="button button-outline" onClick={() => setExpanded(!expanded)}>{expanded ? 'Show selected projects' : 'More things I’ve built'}<ArrowRight size={17} className={expanded ? 'rotate-up' : ''}/></button><span>{expanded ? 'Every project, a new possibility.' : 'Always making. Always learning.'}</span></div>}</section>
      <section id="about" className="about-section section-shell"><div className="about-visual reveal"><div className="about-card"><div className="about-card-top"><span>THE HUMAN BEHIND THE CODE</span><span>↗</span></div><div className="monogram">O<span>Z</span><div className="monogram-asterisk">✳</div></div><div className="about-card-bottom"><span>Om Zala<small>Developer. Thinker. Perpetual learner.</small></span><span className="about-coordinates">22.3072° N<br/>73.1812° E</span></div></div><span className="about-note"><span>↳</span> Based in India. Thinking beyond borders.</span></div><div className="about-copy reveal"><div className="eyebrow"><span className="section-number">02 /</span> A LITTLE ABOUT ME</div><h2>A builder's mind.<br/>A <span className="serif-word">creative soul.</span></h2><p>I like making complicated things feel simple. Whether it’s an enterprise CRM, a learning platform, or an AI-powered workflow, I care about what happens on both sides of the screen.</p><p>I'm a full stack developer based in Vadodara, India. At Kanan.co, I worked on real-world products, collaborated with talented teams, and learned to own the details — from database schemas to that final interaction.</p><p className="about-highlight">Now, I'm looking for my next opportunity to build something that matters.</p><a className="text-link" href="#contact">Let's make something great <ArrowUpRight size={18}/></a></div></section>
      <section className="skills-section section-shell"><div className="skills-heading reveal"><div className="eyebrow"><span className="section-number">THE TOOLKIT /</span> IDEAS NEED GOOD TOOLS</div><h2>My creative <span className="serif-word">stack.</span></h2></div><div className="skills-grid reveal">{[{ icon: Code2, title: 'The interface', subtitle: 'Thoughtful, responsive, alive.', skills: ['React.js', 'JavaScript', 'HTML & CSS', 'Tailwind CSS', 'UI animations'] }, { icon: Layers3, title: 'The engine', subtitle: 'Solid foundations. Room to scale.', skills: ['Node.js', 'Express.js', 'MongoDB', 'MySQL', 'REST APIs', 'RBAC'] }, { icon: Sparkles, title: 'The intelligence', subtitle: 'Less repetition. More possibility.', skills: ['Gemini API', 'Agentic AI', 'Python', 'Prompt engineering', 'API integrations'] }].map(({ icon: Icon, title, subtitle, skills }) => <div className="skill-card" key={title}><span className="skill-icon"><Icon size={22}/></span><h3>{title}</h3><p>{subtitle}</p><div className="skill-tags">{skills.map(s => <span key={s}>{s}</span>)}</div></div>)}</div><div className="tools-line reveal"><span>ALSO IN THE MIX</span><p>Git & GitHub <i/> Postman <i/> Vercel <i/> Google Calendar & Maps APIs <i/> Agile & code reviews</p></div></section>
      <section id="experience" className="experience-section section-shell"><div className="experience-heading reveal"><div className="eyebrow"><span className="section-number">03 /</span> THE JOURNEY SO FAR</div><h2>Real work.<br/>Real <span className="serif-word">growth.</span></h2><p>Learning by building.<br/>Growing with every challenge.</p><a className="text-link" href={resume} download>Get the full résumé <Download size={16}/></a></div><div className="timeline reveal"><article className="timeline-item"><span className="timeline-dot"/><div className="timeline-meta"><span>AUG 2025 — JUL 2026</span><span className="job-type">FULL TIME</span></div><h3>Junior Full Stack Developer</h3><span className="company">Kanan.co <span>· Vadodara, India</span></span><p>Built and maintained MERN applications, contributed to an enterprise CRM spanning 32 departments, and developed AI tools to automate everyday operations.</p><div className="experience-points"><span>Enterprise CRM</span><span>AI automation</span><span>End-to-end delivery</span></div></article><article className="timeline-item"><span className="timeline-dot"/><div className="timeline-meta"><span>MAY 2025 — AUG 2025</span><span className="job-type">INTERNSHIP</span></div><h3>Junior Developer Intern</h3><span className="company">Kanan.co <span>· Vadodara, India</span></span><p>Contributed to full-stack features, built AI-assisted learning modules, and curated 20,000+ practice questions used across multiple educational products.</p><div className="experience-points"><span>EdTech</span><span>Full stack</span><span>AI-assisted learning</span></div></article><article className="timeline-item education"><span className="timeline-dot"/><div className="timeline-meta"><span>EDUCATION · JAN 2025</span><BookOpen size={17}/></div><h3>Diploma in Computer Engineering</h3><span className="company">MSU Polytechnic <span>· Vadodara · CGPA 7.3 / 10</span></span></article></div></section>
      <section id="contact" className="contact-section section-shell"><div className="contact-top reveal"><span className="contact-availability"><span className="status-dot"/> OPEN TO FULL STACK & MERN ROLES</span><span>GREAT THINGS START WITH A CONVERSATION</span></div><div className="contact-main reveal"><h2>Have something<br/>in <span className="serif-word">mind?</span><span className="contact-star">✳</span></h2><a className="contact-orb" href="mailto:omzala635@gmail.com" aria-label="Email Om Zala"><ArrowUpRight/><span>LET'S TALK</span></a></div><div className="contact-bottom reveal"><div><p>A new role, an ambitious idea, or just a hello.<br/>I'd love to hear from you.</p><div className="email-row"><a href="mailto:omzala635@gmail.com">omzala635@gmail.com</a><button className="copy-button" onClick={copyEmail} aria-label="Copy email address">{copied ? <Check size={17}/> : <Copy size={17}/>}</button></div><span className="copy-status" role="status">{copied ? 'Email copied to clipboard.' : copyError ? 'Please select and copy the email address above.' : ''}</span></div><div className="social-links"><a href="https://github.com/Omzala" target="_blank" rel="noreferrer"><Github size={17}/>GitHub<ArrowUpRight size={15}/></a><a href="https://www.linkedin.com/in/om-zala-16aa93308" target="_blank" rel="noreferrer"><Linkedin size={17}/>LinkedIn<ArrowUpRight size={15}/></a><a href={resume} download><Download size={17}/>Résumé<ArrowUpRight size={15}/></a></div></div></section>
    </main>
    <footer className="site-footer section-shell"><a className="wordmark" href="#home">om<span>zala</span><i/></a><span>© {new Date().getFullYear()} Om Zala · Crafted with curiosity.</span><span className="footer-time"><span className="status-dot"/>{time} IST <span>· INDIA</span></span><a className="back-top" href="#home" aria-label="Back to top"><ArrowUpRight size={19}/></a></footer>
    {selected && <ProjectDialog project={selected} onClose={() => setSelected(null)}/>}
  </>;
}

createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
